### ISSUE TITLE
Change intro screen buttons to use the arcade.gui module

### ISSUE THREAD

**Issue by TheRiddler4K** [tobiasbp/python-arcade-tuesday-02#110]
Currenty you can activate the play button without actually pressing it. With the arcade.gui module this will not be a problem. It also has other benefits

**Comment by tobiasbp** [comment]
Good suggestion. Let's do it.

**Comment by TheRiddler4K** [comment]
I have experience with the arcade.gui module so i can do it. However if someone else wants to learn about the module this would be a good opportunity
