### ISSUE TITLE
UFOShot can hit the player several times

### ISSUE THREAD

**Issue by ivan-BRHM** [tobiasbp/python-arcade-tuesday-02#53]
It seems that the ufos shot can hit the player many times over.
This should be fixed by either destroying it when it hits the player, or otherwise prevent it from hitting the player repeatedly.
The immortallity feature sort of cover it but the shot can still hit you after your immortality has run out.

**Comment by tobiasbp** [comment]
I think you should correct this bug @ivan-BRHM . Maybe it's as simple as calling _.kill()_ on the _UfoShot_?

**Comment by TheRiddler4K** [comment]
I am on branch main and in my version of the game this bug is still a problem.

**Comment by TheRiddler4K** [comment]
This is the code that checks if the UFOShot collides with the Player Sprite:
        # checks if ufo shot collides with player
        if any(self.player_sprite.collides_with_list(self.ufo_shot_list)):
            self.player_sprite.lives -= 1
The UFOShot is not killed

**Comment by ivan-BRHM** [comment]
In the origin version of main it functions. If nothing else just copy the origin version.
